// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtjxkyqumefxmatbtfyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0anhreXF1bWVmeG1hdGJ0ZnlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjUwNjIsImV4cCI6MjA3MjE0MTA2Mn0.gVgRNB5ZQMvT_jyxAf1WPiakp_44QAVl1QaV1Xxx3WU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});